# Generated by Django 5.2.7 on 2025-10-24 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor'), ('INFO', 'Info')], default='INFO', max_length=10)),
                ('module_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=255)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('code_snippet', models.TextField(blank=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.analysisrun')),
            ],
        ),
    ]
