# Generated by Django 5.2.7 on 2025-10-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_analysisrun_completed_at_alter_analysisrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
