# Generated by Django 5.2.7 on 2025-11-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_git_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='effort_score',
            field=models.FloatField(default=0.0, help_text="Score d'effort calculé basé sur les issues trouvées."),
        ),
    ]
