# Generated by Django 5.2.7 on 2025-11-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_analysisrun_effort_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
