# Generated by Django 5.2.7 on 2025-11-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_issue_issue_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_code',
            field=models.CharField(blank=True, help_text='Code unique identifiant le type de problème', max_length=20, null=True),
        ),
    ]
